{
 "title": "NexRAN",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UE Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "dl_bytes" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "ul_bytes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "tx_pkts" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "rx_pkts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE PRB Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "dl_prbs" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "ul_prbs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE Packet Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE DL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "dl_cqi" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "dl_mcs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UE UL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" },
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "ul_sinr" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ue" ], "type": "tag" }
     ],
     "measurement": "ue",
     "select": [
      [
       { "params": [ "dl_mcs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NodeB Masks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nodeb" ], "type": "tag" }
     ],
     "measurement": "masks",
     "select": [
      [
       { "params": [ "ul_available_bits" ], "type": "field" }
      ],
      [
       { "params": [ "ul_masked_bits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice Shares",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "share",
     "select": [
      [
       { "params": [ "share" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "dl_bytes" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "ul_bytes" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "tx_pkts" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "rx_pkts" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice PRB Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "dl_prbs" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "ul_prbs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice Packet Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "tx_errors" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "rx_errors" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice DL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "dl_cqi" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "dl_mcs" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slice UL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "ul_sinr" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "slice" ], "type": "tag" }
     ],
     "measurement": "slice",
     "select": [
      [
       { "params": [ "dl_mcs" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}